### PR TITLE
Hide mentions in inline spoilers

### LINKED ISSUE #2033: Mentions are not hidden in spoilers
## Bug Report

**Current Behavior**
User/Post mentions are not hidden in spoilers

**Steps to Reproduce**
1. Create/reply to a discussion
2. In the contents create an inline spoiler and inside that spoiler mention someone or another post
3. See error

**Expected Behavior**
Mentions should be hidden
**Screenshots**
Image

**Environment**
- Flarum version: beta.12
- Website URL: http://discuss.flarum.org
- Browser: [e.g. chrome 67, safari 11] All

**Possible Solution**

This will probably need a fix in the text formatter itself somehow. I haven't quite figured it out yet but I think removing the `spoiler` class as well as the inline styling might fix this.

### PR DESCRIPTION
**Pull request by tankerkiller125**
Fixes https://github.com/flarum/core/issues/2033

image

### CODE REVIEW

**Comment by dsevillamartin** [comment]
Does the mention still properly work when the spoiler is clicked?

**Comment by tankerkiller125** [comment]
Yes

image

**Comment by franzliedke** [comment]
I am afraid this is the wrong place for this code. The markdown extension should not know anything about mentions. :confused: 

Also, why is this `$config->tags['ispoiler']` and not `$config->tags['spoiler']`?

**Comment by tankerkiller125** [comment]
@franzliedke This was a quick patch, we can move this to mentions, we'll need to check to make sure that markdown is enabled before changing the config. Further it's `ispoiler` because it's an inline spoiler issue. `spoiler` is the block spoiler.

**Comment by luceos** [comment]
Whoops. Going to create a checklist for reviewing /merging prs now.

**Comment by dsevillamartin** [comment]
Hm, does this fix only affect mentions or cod it also solve issues with other formatting like color/bg color bbcodes, other bbcodes added by extensions, etc...?

If it solves possible issues with other exts I'd leave it in markdown.

**Comment by tankerkiller125** [comment]
@datitisev Right now I think it only fixes markdown? But I also found an issue regarding emoji be rendered in spoilers earlier today which will also need some LESS fixes.

**Pull request merged**
