### PR TITLE
Add toolbar support for admin panel

### LINKED ISSUE #2874: [Markdown] Toolbar not available in admin frontend
`TextEditor` is now a re-usable component placed in the `common` namespace.

However when using it from the admin panel we don't get access to any of the toolbar benefits provided by the core Markdown extension.

As a workaround it's possible to import Markdown's `forum.js` using the extender `Extend\Assets('admin')` and it works mostly fine because all imported classes are from Flarum's `common` namespace. The only thing that doesn't work with that workaround are the translations for the tooltips which are in the `forum` namespace.

The suggestion is as follows:

- Move the initializer code to a re-usable function in the `common` namespace
- Call the re-usable function from both `forum` and `admin` (there is currently not `admin` js at all)
- Rename translation keys to use `lib` instead of `forum`

### PR DESCRIPTION
**Pull request by therealsujitk**
Fixes [#2874](https://github.com/flarum/core/issues/2874)

**Changes proposed in this pull request:**
This PR adds support to display the markdown toolbar in the admin panel.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)
- [x] Translation keys namespace have to be changed for other languages. (`forum` to `lib`)

### CODE REVIEW

**Comment by askvortsov1** [comment]
Hi, thank you for the PR! A few thoughts:

- Please make sure this passes `flarum-cli audit infra` (via flarum-cli audit infra --fix, probably)
- No dist changes should be included in PRs
- Why is yarn.lock changed?

**Comment by therealsujitk** [comment]
> Please make sure this passes `flarum-cli audit infra` (via flarum-cli audit infra --fix, probably)

This is the error I'm getting

```shell
$ flarum-cli audit infra
 ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load 
 ›   /opt/node/lib/node_modules/@flarum/cli/lib/commands/audit/infra.js
 ›   Code: MODULE_NOT_FOUND
```

> No dist changes should be included in PRs

Oh, I didn't know, I'll remove them.

> Why is yarn.lock changed?

It changed when I ran `yarn install`, I noticed a few packages in the `yarn.lock` file had updated.

**Review by askvortsov1 — APPROVED** [review]
Code LGTM, but I would prefer to avoid modifying the yarn lockfile in this PR if possible, as no new dependencies have been added.

**Comment by therealsujitk** [comment]
Alright I'll remove `yarn.lock`, looks like you've updated it in 57d3f5f4301e75d88809324951b6214cf4cc252f anyway.

**Edit:** I overwrote it with the current `yarn.lock` in master, wasn't sure if I was supposed to do that or overwrite it with the previous version.

**Review by SychO9 — APPROVED** [review]

**Pull request merged**
