### PR TITLE
Make markdown toolbar extensible

### PR DESCRIPTION
**Pull request by davwheat**
This changes the markdown toolbar to use an ItemList.

Totally untested, and was created on my phone and definitely needs a round of code formatting.

### CODE REVIEW

**Comment by askvortsov1** [comment]
Mixed feelings on this approach. If possible, I think it would be better to move the container and itemlist to core, so it could be extended by markdown, bbcode, rich text, and anything else.

**Comment by davwheat** [comment]
Core already has an item list for toolbar buttons as part of the `TextEditor`. Ideally we'd just add the markdown buttons directly as children to this itemlist, allowing us to benefit from more consistent styling for all buttons.

https://github.com/flarum/core/blob/master/js/src/common/components/TextEditor.js#L44-L47

My reasoning for this approach was that removing the containing element (which I would propose we do as there is no reason to have it that I can see) *could* be a breaking change for some themes

**Comment by dsevillamartin** [comment]
> Mixed feelings on this approach. If possible, I think it would be better to move the container and itemlist to core, so it could be extended by markdown, bbcode, rich text, and anything else.

This is basically https://github.com/flarum/core/issues/1872.

**Comment by davwheat** [comment]
Don't we already have that as a possibility with the TextEditor currently?

I've had extensions which add buttons to the text editor toolbar already, and they seem to match all the same styles 🤔

**Comment by dsevillamartin** [comment]
@davwheat Easier to use this logic & have it available in admin as well. I think you can add buttons but the text added to editor is manual? not sure

**Comment by davwheat** [comment]
Ah yeah, I forgot that all the actual content editing is done here too. 👍

**Comment by dsevillamartin** [comment]
I personally think this is a good idea for now - alongside some prettier fixes :P

**Comment by askvortsov1** [comment]
> This is basically [flarum/core#1872](https://github.com/flarum/core/issues/1872).

Right, and I think that would be useful (at least in terms of making editing buttons consistent across all exts).

**Pull request closed without merging**
